// insight.canon.cppm — §8.1 wrapper module (1.5.0). GENERATED by gen_module_wrapper.py,
// hand-verified. Re-exports the package's global-module public surface; defs stay in src/*.cpp
// (.a byte-identical). 1.5.1 will unwrap this into a pure module.
module;
#include "insight/core/types.hpp"
#include "insight/math/det_math.hpp"
#include "insight/tokenization/arena_allocator.hpp"
#include "insight/tokenization/canonical_event.hpp"
#include "insight/tokenization/drain_config.hpp"
#include "insight/tokenization/structural_role_registry.hpp"
#include "insight/tokenization/tokenizer_engine.hpp"
#include "insight/utils/failure_lexicon.hpp"
#include "insight/utils/logger.hpp"
#include "insight/utils/time_utils.hpp"

export module insight.canon;

export namespace insight
{
using insight::AnomalyType;
using insight::Duration;
using insight::EventID;
using insight::LogFormat;
using insight::LogLevel;
using insight::NGram;
using insight::ParseError;
using insight::Severity;
using insight::severity_to_string;
using insight::StructuralRole;
using insight::SubScore;
using insight::TemplateID;
using insight::Timestamp;
using insight::to_string;
using insight::WindowID;
} // namespace insight
export namespace insight::det
{
using insight::det::det_ln_fixed;
using insight::det::det_log2_fixed;
using insight::det::fixed_to_double;
using insight::det::FixedReducer;
using insight::det::kFracBits;
using insight::det::kLn2Fixed;
using insight::det::kOne;
using insight::det::round_div;
} // namespace insight::det
export namespace insight::logging
{
using insight::logging::arena_logger;
using insight::logging::detector_logger;
using insight::logging::drain_logger;
using insight::logging::init_logging;
using insight::logging::kArenaLogger;
using insight::logging::kDebugLogsEnabled;
using insight::logging::kDetectorLogger;
using insight::logging::kDrainLogger;
using insight::logging::kInfoLogsEnabled;
using insight::logging::kParserLogger;
using insight::logging::kPipelineLogger;
using insight::logging::kStrategyLogger;
using insight::logging::kTokenizerLogger;
using insight::logging::kTraceLogsEnabled;
using insight::logging::kWarnLogsEnabled;
using insight::logging::parser_logger;
using insight::logging::pipeline_logger;
using insight::logging::strategy_logger;
using insight::logging::tokenizer_logger;
} // namespace insight::logging
export namespace insight::tokenization
{
using insight::tokenization::arena_numa_node_count;
using insight::tokenization::arena_numa_supported;
using insight::tokenization::ArenaAllocator;
using insight::tokenization::ArenaNumaPolicy;
using insight::tokenization::CanonicalEvent;
using insight::tokenization::DrainConfig;
using insight::tokenization::StructuralRoleRegistry;
using insight::tokenization::Tokenizer;
} // namespace insight::tokenization
export namespace insight::utils
{
using insight::utils::contains_failure_cue;
using insight::utils::contains_warning_cue;
using insight::utils::infer_leading_log_level;
using insight::utils::kDefaultReferenceYear;
using insight::utils::parse_clf_timestamp;
using insight::utils::parse_dotted_date;
using insight::utils::parse_health_app_ts;
using insight::utils::parse_iso8601;
using insight::utils::parse_log_level;
} // namespace insight::utils
